/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "secondary-container": "#b5d0fd",
        tertiary: "#943700",
        "on-secondary-container": "#3e5980",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "surface-container-highest": "#e0e3e5",
        primary: "#004ac6",
        background: "#f7f9fb",
        secondary: "#455f87",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#bc4800",
        "primary-container": "#2563eb",
        "on-primary-fixed": "#00174b",
        surface: "#f7f9fb",
        "on-background": "#191c1e",
        "outline-variant": "#c3c6d7",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-bright": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "surface-dim": "#d8dadc",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "inverse-primary": "#b4c5ff",
        "secondary-fixed": "#d5e3ff",
        "on-primary-container": "#eeefff",
        outline: "#737686",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-high": "#e6e8ea",
        success: "#16a34a",
        "on-success": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        sentinel: "0px 12px 32px -4px rgba(25,28,30,0.06)",
      },
    },
  },
  plugins: [],
};
